[global]
start_port=1080
ports=10
identity_file='.ssh/id_rsa'

[servers]
[servers.lb3]
ipaddr="10.0.0.1"
sites=["google.com", "apple.com"]
[servers.lb4]
ipaddr="10.0.1.1"
sites=["yahoo.co.jp", "x.com"]
