[package]
name = "proxs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
anyhow = "1.0"
tokio = { version = "1", features = ["rt", "macros"] }
hyper = { version = "0.14", features = ["client", "http1"] }
hyperlocal = "0.8"
serde_json = "1.0"
